// Subscribe to plan
document.querySelectorAll('.btn-plan').forEach(btn => {
    btn.onclick = async () => {
        if (!apiKey) {
            showLoginModal();
            return;
        }
        
        const plan = btn.dataset.plan;
        
        if (plan === 'free') {
            alert('Free plan activated! You have 3 free documents to try.');
            return;
        }
        
        if (plan === 'subscription') {
            try {
                const response = await fetch('/api/upgrade-subscription', {
                    method: 'POST',
                    headers: {
                        'Content-Type': 'application/json',
                        'X-API-Key': apiKey
                    }
                });
                
                const session = await response.json();
                
                if (stripe) {
                    const result = await stripe.redirectToCheckout({ sessionId: session.sessionId });
                    if (result.error) {
                        alert(result.error.message);
                    }
                }
            } catch (error) {
                alert('Payment processing failed: ' + error.message);
            }
        } else if (plan === 'pay_as_you_go') {
            const amount = prompt('How many credits would you like to buy?\n\n$1 = 10 documents\nMinimum $10\n\nEnter amount in USD:', '10');
            
            if (amount && amount >= 10) {
                try {
                    const response = await fetch('/api/buy-credits', {
                        method: 'POST',
                        headers: {
                            'Content-Type': 'application/json',
                            'X-API-Key': apiKey
                        },
                        body: JSON.stringify({ amount: parseFloat(amount) })
                    });
                    
                    const session = await response.json();
                    
                    if (stripe) {
                        const result = await stripe.redirectToCheckout({ sessionId: session.sessionId });
                        if (result.error) {
                            alert(result.error.message);
                        }
                    }
                } catch (error) {
                    alert('Payment failed: ' + error.message);
                }
            }
        }
    };
});

// Check user status and show watermark warning if applicable
async function checkUserStatus() {
    if (!apiKey) return;
    
    try {
        const response = await fetch('/api/user-status', {
            headers: { 'X-API-Key': apiKey }
        });
        
        const status = await response.json();
        
        // Show status bar
        const statusBar = document.createElement('div');
        statusBar.className = 'status-bar';
        
        if (status.plan === 'free') {
            statusBar.innerHTML = `
                <span>⚠️ Free trial: ${status.free_remaining} documents remaining (watermarked)</span>
                <button onclick="upgradePrompt()" class="status-upgrade">Upgrade to Remove Watermark →</button>
            `;
        } else if (status.plan === 'pay_as_you_go') {
            statusBar.innerHTML = `
                <span>💰 Credits: $${status.credits.toFixed(2)} (${status.files_from_credits} documents left)</span>
                <button onclick="buyMoreCredits()" class="status-upgrade">Buy More Credits →</button>
            `;
        } else if (status.plan === 'subscription') {
            statusBar.innerHTML = `
                <span>✨ Premium Active - No Watermarks! Unlimited Documents</span>
            `;
        }
        
        const existingBar = document.querySelector('.status-bar');
        if (existingBar) existingBar.remove();
        
        document.querySelector('.generator').insertBefore(statusBar, document.querySelector('.generator').firstChild);
        
    } catch (error) {
        console.error('Status check failed:', error);
    }
}

// Show watermark warning before PDF export
document.getElementById('exportPDF').onclick = async () => {
    if (!currentDocId) return;
    
    // Check if document has watermark
    const resultDiv = document.getElementById('result');
    const hasWatermark = resultDiv.dataset.hasWatermark === 'true';
    
    if (hasWatermark) {
        const confirmExport = confirm('⚠️ This document will have a watermark "Generated by ABSON CV Generator".\n\nUpgrade to $1/month or $0.10/file to remove watermarks.\n\nContinue with watermark?');
        if (!confirmExport) {
            // Offer upgrade
            const upgrade = confirm('Would you like to upgrade to remove watermarks?');
            if (upgrade) {
                document.querySelector('[data-plan="subscription"]').click();
            }
            return;
        }
    }
    
    try {
        const response = await fetch(`/api/export-pdf/${currentDocId}`, {
            headers: { 'X-API-Key': apiKey }
        });
        
        const blob = await response.blob();
        const url = window.URL.createObjectURL(blob);
        const a = document.createElement('a');
        a.href = url;
        a.download = `document_${currentDocId}.pdf`;
        a.click();
    } catch (error) {
        alert('Export failed: ' + error.message);
    }
};

// Update generate function to show watermark warning
async function generateDocument(endpoint, data, type) {
    const generateBtn = document.querySelector(`#${type}Form .btn-generate`);
    const originalText = generateBtn.textContent;
    generateBtn.textContent = 'Generating...';
    generateBtn.disabled = true;
    
    try {
        const response = await fetch(endpoint, {
            method: 'POST',
            headers: {
                'Content-Type': 'application/json',
                'X-API-Key': apiKey
            },
            body: JSON.stringify(data)
        });
        
        const result = await response.json();
        
        if (response.status === 402 || result.need_upgrade) {
            alert(result.error || 'Please upgrade to continue generating documents.');
            return;
        }
        
        if (result.error) {
            alert('Error: ' + result.error);
            return;
        }
        
        currentDocId = result.cv_id || result.cover_id;
        resultContent.innerHTML = result.content.replace(/\n/g, '<br>');
        
        // Show watermark warning if applicable
        let watermarkWarning = '';
        if (result.has_watermark) {
            watermarkWarning = '<div class="watermark-warning">⚠️ This document will have a watermark when exported. <a href="#" onclick="upgradePrompt()">Upgrade to remove</a></div>';
        }
        
        resultDiv.innerHTML = watermarkWarning + resultDiv.innerHTML;
        resultDiv.style.display = 'block';
        resultDiv.dataset.hasWatermark = result.has_watermark;
        
        // Show remaining info
        if (result.free_remaining !== undefined) {
            alert(`Document generated! You have ${result.free_remaining} free documents remaining.`);
        } else if (result.credits_remaining !== undefined) {
            alert(`Document generated! Credits remaining: $${result.credits_remaining.toFixed(2)} (${Math.floor(result.credits_remaining / 0.10)} documents left)`);
        }
        
        // Refresh status
        checkUserStatus();
        
    } catch (error) {
        alert('Generation failed: ' + error.message);
    } finally {
        generateBtn.textContent = originalText;
        generateBtn.disabled = false;
    }
}

window.upgradePrompt = function() {
    const choice = confirm('Choose upgrade option:\n\nOK - $1/month subscription\nCancel - $0.10 per file (min $10)');
    if (choice) {
        document.querySelector('[data-plan="subscription"]').click();
    } else {
        document.querySelector('[data-plan="pay_as_you_go"]').click();
    }
};

window.buyMoreCredits = function() {
    document.querySelector('[data-plan="pay_as_you_go"]').click();
};

// Call status check after login
checkUserStatus();
