from flask import Flask, request, jsonify, send_file, render_template_string
from flask_cors import CORS
import openai
import stripe
import os
from reportlab.pdfgen import canvas
from reportlab.lib.pagesizes import letter
from reportlab.lib.units import inch
from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase.ttfonts import TTFont
from io import BytesIO
import json
from datetime import datetime
from functools import wraps
import secrets
import hashlib

app = Flask(__name__, static_folder='../frontend', static_url_path='')
CORS(app)

# Configuration
app.config['SECRET_KEY'] = os.getenv('SECRET_KEY', secrets.token_hex(32))
openai.api_key = os.getenv('OPENAI_API_KEY')
stripe.api_key = os.getenv('STRIPE_API_KEY')

# Pricing plans
PLANS = {
    'free': {
        'monthly_price': 0, 
        'per_file_price': 0,
        'has_watermark': True,
        'max_free_files': 3  # 3 free files total, then must pay
    },
    'subscription': {
        'monthly_price': 1.00,  # $1 per month
        'per_file_price': 0,
        'has_watermark': False,
        'stripe_price_id': 'price_subscription_1usd'
    },
    'pay_as_you_go': {
        'monthly_price': 0,
        'per_file_price': 0.10,  # $0.10 per file
        'has_watermark': False,
        'stripe_price_id': None  # Handled via credits
    }
}

# User database (use real DB in production)
users = {}
user_credits = {}  # Store prepaid credits
generations = {}

def require_auth(f):
    @wraps(f)
    def decorated_function(*args, **kwargs):
        api_key = request.headers.get('X-API-Key')
        if not api_key or api_key not in users:
            return jsonify({'error': 'Invalid API key'}), 401
        request.user = users[api_key]
        return f(*args, **kwargs)
    return decorated_function

def can_generate(user):
    """Check if user can generate a document based on their plan"""
    plan = user['plan']
    current_month = datetime.now().strftime('%Y-%m')
    
    if plan == 'free':
        # Track total free files generated
        if user.get('free_files_used', 0) >= PLANS['free']['max_free_files']:
            return False, "Free limit reached. Please upgrade to continue."
        return True, None
    
    elif plan == 'subscription':
        # Check if subscription is active
        if user.get('subscription_active', False):
            # Check monthly limit? (Optional: add fair usage limit)
            if current_month not in user['usage']:
                user['usage'][current_month] = 0
            if user['usage'][current_month] >= 100:  # 100 files/month fair usage
                return False, "Monthly fair usage limit reached. Contact support if you need more."
            return True, None
        else:
            return False, "Subscription expired. Please renew."
    
    elif plan == 'pay_as_you_go':
        # Check credits
        if user_credits.get(user['email'], 0) >= 0.10:  # At least $0.10 credit
            return True, None
        else:
            return False, "Insufficient credits. Please purchase more credits."
    
    return False, "Invalid plan"

def deduct_credits(user):
    """Deduct credits for pay-as-you-go users"""
    if user['plan'] == 'pay_as_you_go':
        current_credits = user_credits.get(user['email'], 0)
        user_credits[user['email']] = current_credits - 0.10
        
    elif user['plan'] == 'free':
        user['free_files_used'] = user.get('free_files_used', 0) + 1
        
    elif user['plan'] == 'subscription':
        current_month = datetime.now().strftime('%Y-%m')
        user['usage'][current_month] = user['usage'].get(current_month, 0) + 1

def add_watermark_to_pdf(pdf_buffer, watermark_text="Generated by ABSON CV Generator"):
    """Add watermark to PDF"""
    # Create a new PDF with watermark
    packet = BytesIO()
    can = canvas.Canvas(packet, pagesize=letter)
    width, height = letter
    
    # Add watermark text diagonally
    can.saveState()
    can.setFont('Helvetica', 20)
    can.setFillColorRGB(0.7, 0.7, 0.7, alpha=0.3)
    can.translate(width/2, height/2)
    can.rotate(45)
    can.drawCentredString(0, 0, watermark_text)
    can.restoreState()
    can.save()
    
    # Merge watermarks
    packet.seek(0)
    return packet

@app.route('/')
def serve_frontend():
    with open('../frontend/index.html', 'r') as f:
        return render_template_string(f.read())

@app.route('/api/register', methods=['POST'])
def register():
    data = request.json
    api_key = secrets.token_urlsafe(32)
    
    users[api_key] = {
        'email': data['email'],
        'plan': 'free',  # Start with free plan
        'free_files_used': 0,
        'subscription_active': False,
        'usage': {},
        'created_at': datetime.now().isoformat()
    }
    
    # Give 3 free files worth of credits for pay-as-you-go
    user_credits[data['email']] = 0
    
    return jsonify({
        'api_key': api_key, 
        'plan': 'free',
        'free_remaining': 3  # 3 free files
    })

@app.route('/api/generate-cv', methods=['POST'])
@require_auth
def generate_cv():
    user = request.user
    
    can_gen, message = can_generate(user)
    if not can_gen:
        return jsonify({'error': message, 'need_upgrade': True}), 402
    
    data = request.json
    
    prompt = f"""
    Create a professional CV/resume with the following information:
    Name: {data.get('name')}
    Email: {data.get('email')}
    Phone: {data.get('phone')}
    Experience: {data.get('experience')}
    Education: {data.get('education')}
    Skills: {data.get('skills')}
    Template Style: {data.get('template', 'modern')}
    
    Format the CV professionally with clear sections. Use markdown formatting.
    """
    
    try:
        response = openai.ChatCompletion.create(
            model="gpt-3.5-turbo",
            messages=[{"role": "user", "content": prompt}],
            max_tokens=1000
        )
        
        generated_cv = response.choices[0].message.content
        
        # Deduct credits/usage
        deduct_credits(user)
        
        cv_id = secrets.token_urlsafe(16)
        generations[cv_id] = {
            'content': generated_cv, 
            'type': 'cv', 
            'user': user['email'],
            'has_watermark': PLANS[user['plan']]['has_watermark']
        }
        
        response_data = {
            'cv_id': cv_id,
            'content': generated_cv,
            'has_watermark': PLANS[user['plan']]['has_watermark']
        }
        
        # Add plan-specific info
        if user['plan'] == 'free':
            response_data['free_remaining'] = max(0, 3 - user.get('free_files_used', 0))
        elif user['plan'] == 'pay_as_you_go':
            response_data['credits_remaining'] = user_credits.get(user['email'], 0)
        
        return jsonify(response_data)
        
    except Exception as e:
        return jsonify({'error': str(e)}), 500

@app.route('/api/generate-cover', methods=['POST'])
@require_auth
def generate_cover():
    user = request.user
    
    can_gen, message = can_generate(user)
    if not can_gen:
        return jsonify({'error': message, 'need_upgrade': True}), 402
    
    data = request.json
    
    prompt = f"""
    Write a professional cover letter for:
    Position: {data.get('position')}
    Company: {data.get('company')}
    Candidate Name: {data.get('name')}
    Experience Summary: {data.get('experience')}
    Key Skills: {data.get('skills')}
    
    Make it persuasive and tailored to the position. Use markdown formatting.
    """
    
    try:
        response = openai.ChatCompletion.create(
            model="gpt-3.5-turbo",
            messages=[{"role": "user", "content": prompt}],
            max_tokens=800
        )
        
        generated_cover = response.choices[0].message.content
        
        deduct_credits(user)
        
        cover_id = secrets.token_urlsafe(16)
        generations[cover_id] = {
            'content': generated_cover, 
            'type': 'cover', 
            'user': user['email'],
            'has_watermark': PLANS[user['plan']]['has_watermark']
        }
        
        response_data = {
            'cover_id': cover_id,
            'content': generated_cover,
            'has_watermark': PLANS[user['plan']]['has_watermark']
        }
        
        if user['plan'] == 'free':
            response_data['free_remaining'] = max(0, 3 - user.get('free_files_used', 0))
        elif user['plan'] == 'pay_as_you_go':
            response_data['credits_remaining'] = user_credits.get(user['email'], 0)
        
        return jsonify(response_data)
        
    except Exception as e:
        return jsonify({'error': str(e)}), 500

@app.route('/api/export-pdf/<doc_id>', methods=['GET'])
@require_auth
def export_pdf(doc_id):
    if doc_id not in generations:
        return jsonify({'error': 'Document not found'}), 404
    
    doc = generations[doc_id]
    
    # Create simple PDF with content
    buffer = BytesIO()
    c = canvas.Canvas(buffer, pagesize=letter)
    width, height = letter
    
    # Add content
    y = height - 50
    c.setFont("Helvetica", 12)
    
    for line in doc['content'].split('\n'):
        if y < 50:
            c.showPage()
            y = height - 50
            c.setFont("Helvetica", 12)
        
        # Handle long lines
        if len(line) > 80:
            words = line.split()
            current_line = ""
            for word in words:
                if len(current_line + word) < 80:
                    current_line += word + " "
                else:
                    c.drawString(50, y, current_line)
                    y -= 15
                    current_line = word + " "
            if current_line:
                c.drawString(50, y, current_line)
                y -= 15
        else:
            c.drawString(50, y, line)
            y -= 15
    
    # Add watermark if needed
    if doc['has_watermark']:
        c.saveState()
        c.setFont("Helvetica", 16)
        c.setFillColorRGB(0.5, 0.5, 0.5, alpha=0.3)
        c.translate(width/2, height/2)
        c.rotate(45)
        c.drawCentredString(0, 0, "Generated by ABSON CV Generator")
        c.restoreState()
    
    c.save()
    buffer.seek(0)
    
    return send_file(
        buffer,
        as_attachment=True,
        download_name=f"{doc['type']}_{doc_id}.pdf",
        mimetype='application/pdf'
    )

@app.route('/api/upgrade-subscription', methods=['POST'])
@require_auth
def upgrade_subscription():
    user = request.user
    
    try:
        checkout_session = stripe.checkout.Session.create(
            payment_method_types=['card'],
            line_items=[{
                'price': PLANS['subscription']['stripe_price_id'],
                'quantity': 1,
            }],
            mode='subscription',
            success_url='https://yourdomain.com/success?session_id={CHECKOUT_SESSION_ID}',
            cancel_url='https://yourdomain.com/cancel',
            client_reference_id=user['email'],
            metadata={
                'plan': 'subscription'
            }
        )
        return jsonify({'sessionId': checkout_session.id})
    except Exception as e:
        return jsonify({'error': str(e)}), 500

@app.route('/api/buy-credits', methods=['POST'])
@require_auth
def buy_credits():
    user = request.user
    data = request.json
    amount = data.get('amount', 10)  # Amount in dollars, minimum $10
    
    try:
        # Convert dollars to cents for Stripe
        amount_cents = int(amount * 100)
        
        checkout_session = stripe.checkout.Session.create(
            payment_method_types=['card'],
            line_items=[{
                'price_data': {
                    'currency': 'usd',
                    'product_data': {
                        'name': f'{amount} Credits for CV/Letter Generation',
                        'description': f'Get {amount * 10} document generations (${amount} = {amount * 10} files)',
                    },
                    'unit_amount': amount_cents,
                },
                'quantity': 1,
            }],
            mode='payment',
            success_url='https://yourdomain.com/credits-success?session_id={CHECKOUT_SESSION_ID}',
            cancel_url='https://yourdomain.com/cancel',
            client_reference_id=user['email'],
            metadata={
                'credit_amount': str(amount * 10),  # $1 = 10 files
                'dollar_amount': str(amount)
            }
        )
        return jsonify({'sessionId': checkout_session.id})
    except Exception as e:
        return jsonify({'error': str(e)}), 500

@app.route('/api/webhook/stripe', methods=['POST'])
def stripe_webhook():
    payload = request.get_data(as_text=True)
    sig_header = request.headers.get('Stripe-Signature')
    
    try:
        event = stripe.Webhook.construct_event(
            payload, sig_header, os.getenv('STRIPE_WEBHOOK_SECRET')
        )
        
        if event['type'] == 'checkout.session.completed':
            session = event['data']['object']
            customer_email = session['client_reference_id']
            
            # Update user based on purchase type
            if 'subscription' in session.get('metadata', {}).get('plan', ''):
                # Update to subscription plan
                for api_key, user in users.items():
                    if user['email'] == customer_email:
                        user['plan'] = 'subscription'
                        user['subscription_active'] = True
                        break
            else:
                # Add credits
                credit_amount = float(session['metadata'].get('credit_amount', 0))
                user_credits[customer_email] = user_credits.get(customer_email, 0) + credit_amount
                
                # Update plan if they have credits and were free
                for api_key, user in users.items():
                    if user['email'] == customer_email and user['plan'] == 'free':
                        user['plan'] = 'pay_as_you_go'
                        break
        
        elif event['type'] == 'customer.subscription.deleted':
            # Handle subscription cancellation
            subscription = event['data']['object']
            customer_email = subscription['metadata'].get('email')
            if customer_email:
                for api_key, user in users.items():
                    if user['email'] == customer_email:
                        user['subscription_active'] = False
                        user['plan'] = 'pay_as_you_go' if user_credits.get(customer_email, 0) > 0 else 'free'
                        break
        
        return jsonify({'status': 'success'})
    except Exception as e:
        return jsonify({'error': str(e)}), 400

@app.route('/api/user-status', methods=['GET'])
@require_auth
def user_status():
    user = request.user
    credits = user_credits.get(user['email'], 0)
    
    return jsonify({
        'plan': user['plan'],
        'free_files_used': user.get('free_files_used', 0),
        'free_remaining': max(0, 3 - user.get('free_files_used', 0)),
        'credits': credits,
        'files_from_credits': int(credits / 0.10) if credits > 0 else 0,
        'subscription_active': user.get('subscription_active', False)
    })

if __name__ == '__main__':
    app.run(debug=True, port=5000)
